export type Epic='iliad'|'odyssey';export type Order='told'|'happened';export type Episode={id:string;epic:Epic;book:string;chronology:number;title:string;place:string;summary:string;people:string[];theme:string}
export const episodes:Episode[]=[
 {id:'quarrel',epic:'iliad',book:'1',chronology:1,title:'The quarrel',place:'Greek camp',summary:'Agamemnon dishonors Achilles. Achilles withdraws, and the army pays for a conflict between pride and power.',people:['Achilles','Agamemnon','Briseis'],'theme':'rage'},
 {id:'walls',epic:'iliad',book:'6',chronology:2,title:'Hector at the walls',place:'Troy',summary:'Hector returns inside Troy and meets Andromache and their child before choosing duty and battle again.',people:['Hector','Andromache'],'theme':'family'},
 {id:'patroclus',epic:'iliad',book:'16',chronology:3,title:'Patroclus wears the armor',place:'Battlefield',summary:'Patroclus enters battle in Achilles’ armor, drives back the Trojans, goes too far, and is killed by Hector.',people:['Patroclus','Hector','Achilles'],'theme':'friendship'},
 {id:'return',epic:'iliad',book:'18–19',chronology:4,title:'Achilles returns',place:'Shore and camp',summary:'Grief turns Achilles back toward war. New armor is made, and rage narrows toward Hector.',people:['Achilles','Thetis','Hephaestus'],'theme':'grief'},
 {id:'duel',epic:'iliad',book:'22',chronology:5,title:'Hector faces Achilles',place:'Walls of Troy',summary:'Hector stands outside the walls. Achilles kills him and refuses the ordinary mercy owed to the dead.',people:['Achilles','Hector','Priam'],'theme':'rage'},
 {id:'priam',epic:'iliad',book:'24',chronology:6,title:'A father crosses the lines',place:'Achilles’ shelter',summary:'Priam risks everything to ask for Hector’s body. Enemy and killer recognize one another through shared grief.',people:['Priam','Achilles','Hector'],'theme':'mercy'},
 {id:'ithaca',epic:'odyssey',book:'1–4',chronology:8,title:'A house without its king',place:'Ithaca',summary:'Suitors consume Odysseus’ household. Telemachus begins searching for news while Penelope delays a forced choice.',people:['Penelope','Telemachus','Athena'],'theme':'home'},
 {id:'calypso',epic:'odyssey',book:'5',chronology:7,title:'The last island',place:'Ogygia',summary:'After years held by Calypso, Odysseus is released. A storm destroys his raft before he reaches new shores.',people:['Odysseus','Calypso','Poseidon'],'theme':'home'},
 {id:'phaeacia',epic:'odyssey',book:'6–8',chronology:7.5,title:'The stranger is welcomed',place:'Scheria',summary:'Nausicaa and the Phaeacians receive an unknown traveler. Songs of Troy finally move him to reveal his name.',people:['Odysseus','Nausicaa','Alcinous'],'theme':'hospitality'},
 {id:'cyclops',epic:'odyssey',book:'9',chronology:1,title:'The Cyclops',place:'Land of the Cyclopes',summary:'In a story told later, cunning saves Odysseus from Polyphemus—but pride makes him reveal his name.',people:['Odysseus','Polyphemus','Poseidon'],'theme':'identity'},
 {id:'circe',epic:'odyssey',book:'10–11',chronology:2,title:'Circe and the dead',place:'Aeaea / Underworld',summary:'Companions are transformed and restored. Odysseus then seeks knowledge among the dead before sailing on.',people:['Odysseus','Circe','Tiresias'],'theme':'knowledge'},
 {id:'sirens',epic:'odyssey',book:'12',chronology:3,title:'The impossible passage',place:'Sirens / Scylla',summary:'Odysseus hears the Sirens while bound to the mast, then must choose a route where loss cannot be avoided.',people:['Odysseus','Scylla','Sirens'],'theme':'choice'},
 {id:'return-ithaca',epic:'odyssey',book:'13–16',chronology:9,title:'Home, unrecognized',place:'Ithaca',summary:'Odysseus returns disguised. Recognition arrives slowly, first with Telemachus, while a plan forms.',people:['Odysseus','Telemachus','Athena'],'theme':'identity'},
 {id:'bow',epic:'odyssey',book:'19–22',chronology:10,title:'The bow and the reckoning',place:'Great hall',summary:'Penelope sets the bow contest. The stranger strings the weapon, reveals himself, and the household erupts in violence.',people:['Odysseus','Penelope','Suitors'],'theme':'justice'},
 {id:'olive',epic:'odyssey',book:'23',chronology:11,title:'The rooted bed',place:'Odysseus’ chamber',summary:'Penelope tests the stranger with a secret only her husband would know: a bed built around a living olive tree.',people:['Penelope','Odysseus'],'theme':'home'},
]
export const forEpic=(epic:Epic,order:Order)=>episodes.filter(e=>e.epic===epic).sort((a,b)=>order==='happened'?a.chronology-b.chronology:episodes.indexOf(a)-episodes.indexOf(b))
export const findEpisode=(id:string)=>episodes.find(e=>e.id===id)!
export const story=[
 {epic:'iliad' as Epic,id:'quarrel',title:'The war is already nine years old.',body:'The Iliad does not begin with Helen’s departure or end with the wooden horse. It opens late, with a quarrel inside the Greek camp.',note:'Twenty-four books focus on a short span in the tenth year of the war.'},
 {epic:'iliad' as Epic,id:'patroclus',title:'Rage creates an empty place.',body:'Achilles’ withdrawal changes every life around him. Patroclus steps into that absence wearing his friend’s armor.',note:'Epic action is a chain of choices, consequences, grief, and recognition.'},
 {epic:'iliad' as Epic,id:'priam',title:'The poem ends with an enemy welcomed.',body:'Priam enters Achilles’ shelter. A father and his son’s killer mourn together. The Iliad closes with Hector’s funeral—not Troy’s fall.',note:'The horse belongs to the wider Trojan War tradition and is recalled in the Odyssey.'},
 {epic:'odyssey' as Epic,id:'ithaca',title:'The next poem begins near the end.',body:'Odysseus has been gone twenty years: ten at war and ten returning. The Odyssey begins with his family and a home under pressure.',note:'The first four books follow Telemachus before Odysseus appears.'},
 {epic:'odyssey' as Epic,id:'cyclops',title:'Then the road folds backward.',body:'At a welcoming court, Odysseus narrates the Cyclops, Circe, the Underworld, Sirens, and shipwrecks as memories.',note:'Switching from “told” to “happened” reveals the poem’s large flashback.'},
 {epic:'odyssey' as Epic,id:'olive',title:'Recognition completes the journey.',body:'Home is not merely a location. Penelope’s test proves a shared history that disguise, distance, and storytelling cannot counterfeit.',note:'Both epics end with fragile human order restored after violence.'},
]
