import {useEffect,useMemo,useState} from 'react'; import {codons,nextPhase,phases,story,template,transcribe,translate,type Phase} from './model'

function Brand({lab=false}:{lab?:boolean}){return <span className="brand"><i/>INSIDE ONE CELL {lab&&<em>LAB</em>}<b>04</b></span>}

function CellWorld({phase,zoom=0}:{phase:Phase,zoom?:number}){
 const index=phases.indexOf(phase), scale=1+index*.28+zoom*2.4
 return <div className={`world phase-${phase}`} style={{'--scale':scale} as React.CSSProperties} aria-label={`Biological model: ${phase}`}>
  <div className="cell"><i className="membrane"/><i className="nucleus"/><i className="nucleolus"/><i className="mito m1"/><i className="mito m2"/><i className="golgi"/><i className="vesicle v1"/><i className="vesicle v2"/>
   <div className="dna"><i/><i/><i/><i/><i/><i/></div><div className="polymerase"/><div className="rna">AUG · CCU · GGA · UGA</div><div className="pore"/>
   <div className="ribosome"><i/><b/></div><div className="chain">{[0,1,2,3,4,5,6,7].map(n=><i key={n}/>)}</div><div className="protein">{[0,1,2,3,4].map(n=><i key={n}/>)}</div>
  </div><div className="scale-label"><b>{story[index].kicker}</b><span>visual scale changes between scenes</span></div>
 </div>
}

function Sequence({phase}:{phase:Phase}){const rna=transcribe(template), words=translate(rna);return <section className="sequence" aria-live="polite"><p>ONE SHORT MODEL SEQUENCE</p><div className="letters dna-row"><b>DNA</b>{template.split('').map((x,i)=><i key={i}>{x}</i>)}</div>{phases.indexOf(phase)>=3&&<div className="letters rna-row"><b>RNA</b>{rna.split('').map((x,i)=><i key={i}>{x}</i>)}</div>}{phases.indexOf(phase)>=5&&<div className="codons"><b>READ</b>{codons(rna).map((x,i)=><span key={i}>{x}<em>{words[i]}</em></span>)}</div>}</section>}

function Info({close}:{close:()=>void}){return <div className="scrim"><section className="info"><button className="close" onClick={close} aria-label="Close">×</button><p className="eyebrow">MODEL & LIMITS</p><h2>A true order, radically compressed.</h2><p>The molecular sequence is real in outline. Shapes, colors, spacing, speed, and simultaneous visibility are explanatory choices. A living cell is crowded, stochastic, three-dimensional, chemically specific, and vastly more interconnected.</p><dl><div><dt>Cell</dt><dd>A generalized animal-cell composition. Organelles vary greatly across cell types and are not static furniture.</dd></div><div><dt>Genome</dt><dd>Humans have roughly three billion DNA base pairs and about 20,000 protein-coding genes. A single illustrated gene cannot show genome packing or regulation faithfully.</dd></div><div><dt>Expression</dt><dd>Control can occur during transcription, RNA processing, transport, translation, degradation, and protein activity.</dd></div><div><dt>Protein</dt><dd>Folding is not calculated here. The final form is a poetic symbol for a functional molecule.</dd></div></dl><h3>Scientific starting points</h3><a href="https://www.genome.gov/about-genomics/teaching-tools/Transcription-Translation" target="_blank">NHGRI: transcription and translation ↗</a><a href="https://www.genome.gov/about-genomics/fact-sheets/Deoxyribonucleic-Acid-Fact-Sheet" target="_blank">NHGRI: DNA facts ↗</a><a href="https://www.ncbi.nlm.nih.gov/books/NBK26885/" target="_blank">NCBI: control of gene expression ↗</a><a href="https://www.ncbi.nlm.nih.gov/books/NBK26907/" target="_blank">NCBI: cellular compartments ↗</a><button className="primary" onClick={close}>Return to the cell</button></section></div>}

function Lab(){const [phase,setPhase]=useState<Phase>('cell'),[zoom,setZoom]=useState(0),[auto,setAuto]=useState(false);useEffect(()=>{if(!auto||phase==='fold'){setAuto(false);return}const t=setTimeout(()=>setPhase(nextPhase(phase)),1250);return()=>clearTimeout(t)},[auto,phase]);return <><CellWorld phase={phase} zoom={zoom}/><nav className="phase-nav">{phases.map((p,i)=><button key={p} onClick={()=>setPhase(p)} className={p===phase?'active':''}><span>0{i+1}</span>{p}</button>)}</nav><section className="lab-panel"><p className="eyebrow">EXPRESS ONE GENE</p><h2>{phase==='fold'?'Information has become structure.':story[phases.indexOf(phase)].title}</h2><button className="primary" onClick={()=>{if(phase==='fold')setPhase('cell');else{setAuto(true);setPhase(nextPhase(phase))}}}>{phase==='fold'?'Begin again':'Continue expression'} →</button><label>Magnification <input aria-label="Magnification" type="range" min="0" max="1" step=".01" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label></section><Sequence phase={phase}/></>}

export default function App(){const [state,setState]=useState<'landing'|'guided'|'lab'>('landing'),[step,setStep]=useState(0),[info,setInfo]=useState(false);const phase=useMemo(()=>story[step].phase,[step]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if(state==='guided'&&e.key==='ArrowRight'){step===story.length-1?setState('lab'):setStep(v=>v+1)}if(state==='guided'&&e.key==='ArrowLeft')setStep(v=>Math.max(0,v-1));if(e.key==='Escape')setInfo(false)};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[state,step]);if(state==='landing')return <main className="landing"><header><Brand/></header><div className="hero-cell" aria-hidden="true"><div className="orb"><i/><i/><i/><b/></div></div><section className="hero"><p className="eyebrow">A JOURNEY FROM BOUNDARY TO MOLECULE</p><h1>A city smaller<br/>than a grain <em>of dust.</em></h1><p>Enter one living cell. Open one gene. Follow information until it becomes something that can act.</p><button className="primary" onClick={()=>setState('guided')}>Enter the cell <span>→</span></button><button className="secondary" onClick={()=>setState('lab')}>Open expression lab</button><small>Seven moments · at your pace · scientifically grounded</small></section><footer>Shapes, time, and scale are amplified. The biological order is real.</footer></main>;return <main className={`experience ${state}`}><header className="top"><Brand lab={state==='lab'}/><button onClick={()=>state==='guided'?setState('lab'):setInfo(true)}>{state==='guided'?'Skip to lab →':'Model & limits ?'}</button></header>{state==='guided'?<><CellWorld phase={phase}/><section className="story" key={step}><span>{String(step+1).padStart(2,'0')} / 07 · {story[step].kicker}</span><h2>{story[step].title}</h2><p>{story[step].body}</p><small>{story[step].note}</small><button onClick={()=>step===story.length-1?setState('lab'):setStep(v=>v+1)}>{step===story.length-1?'Enter the laboratory':'Continue'} →</button></section><nav className="story-nav"><button aria-label="Previous" disabled={!step} onClick={()=>setStep(v=>Math.max(0,v-1))}>←</button><i>{step+1}/7</i><button aria-label="Next" onClick={()=>step===6?setState('lab'):setStep(v=>v+1)}>→</button></nav><div className="progress" style={{'--p':`${(step+1)/7*100}%`} as React.CSSProperties}/></>:<Lab/>}{info&&<Info close={()=>setInfo(false)}/>}<div className="grain"/></main>}
