import{Canvas}from'@react-three/fiber';import{Line,OrbitControls,Stars}from'@react-three/drei';import{DoubleSide,Quaternion,Vector3}from'three';import{EARTH_POSITION,MOON_ORBIT_RADIUS,SEASON_ORBIT_RADIUS,SUN_POSITION,moonPosition,seasonEarthPosition,type Mode,type Vec3}from'./model'

function Orbit({radius=MOON_ORBIT_RADIUS}:{radius?:number}){return <mesh rotation={[Math.PI/2,0,0]}><ringGeometry args={[radius-.006,radius+.006,128]}/><meshBasicMaterial color="#536077" transparent opacity={.45} side={DoubleSide}/></mesh>}

function Earth({rotation=0}:{rotation?:number}){return <group rotation={[0,0,-23.4*Math.PI/180]}><mesh rotation={[0,rotation,0]} castShadow receiveShadow><sphereGeometry args={[.72,64,64]}/><meshStandardMaterial color="#163f58" roughness={.72}/></mesh><mesh rotation={[0,rotation+.4,0]}><sphereGeometry args={[.725,32,32]}/><meshStandardMaterial color="#60a889" wireframe transparent opacity={.16}/></mesh><mesh position={[0,.96,0]}><cylinderGeometry args={[.012,.012,1.9,8]}/><meshBasicMaterial color="#91b6d5" transparent opacity={.7}/></mesh></group>}

function ShadowCone({origin,direction,length,startRadius,endRadius,color,opacity}:{origin:Vec3;direction:Vec3;length:number;startRadius:number;endRadius:number;color:string;opacity:number}){const d=new Vector3(...direction).normalize(),q=new Quaternion().setFromUnitVectors(new Vector3(0,1,0),d),p=new Vector3(...origin).addScaledVector(d,length/2);return <mesh position={p} quaternion={q} renderOrder={1}><cylinderGeometry args={[endRadius,startRadius,length,48,1,true]}/><meshBasicMaterial color={color} transparent opacity={opacity} side={DoubleSide} depthWrite={false}/></mesh>}

function EclipseShadows({moon,earth,sun,moonAngle}:{moon:Vec3;earth:Vec3;sun:Vec3;moonAngle:number}){if(Math.cos(moonAngle)>=0){const direction:Vec3=[moon[0]-sun[0],moon[1]-sun[1],moon[2]-sun[2]];return <><ShadowCone origin={moon} direction={direction} length={2.35} startRadius={.27} endRadius={.02} color="#18334c" opacity={.42}/><ShadowCone origin={moon} direction={direction} length={2.35} startRadius={.29} endRadius={.86} color="#d5b67a" opacity={.055}/></>}const direction:Vec3=[earth[0]-sun[0],earth[1]-sun[1],earth[2]-sun[2]];return <><ShadowCone origin={earth} direction={direction} length={3.1} startRadius={.7} endRadius={.31} color="#172b45" opacity={.46}/><ShadowCone origin={earth} direction={direction} length={3.1} startRadius={.72} endRadius={1.13} color="#d5b67a" opacity={.045}/></>}

function TideFields({moonAngle}:{moonAngle:number}){return <><mesh position={EARTH_POSITION} scale={[1.2,1,1]}><sphereGeometry args={[.76,32,32]}/><meshBasicMaterial color="#dfb766" wireframe transparent opacity={.13}/></mesh><mesh position={EARTH_POSITION} rotation={[0,moonAngle,0]} scale={[1.32,1,1]}><sphereGeometry args={[.76,32,32]}/><meshBasicMaterial color="#66b7de" wireframe transparent opacity={.25}/></mesh></>}

function Scene({mode,value,node}:{mode:Mode;value:number;node:number}){const a=value*Math.PI*2,season=mode==='seasons',showMoon=mode==='phases'||mode==='eclipses'||mode==='tides',earthPos:Vec3=season?seasonEarthPosition(a):EARTH_POSITION,sunPos:Vec3=season?[0,0,0]:SUN_POSITION,moonAngle=a,moon=moonPosition(moonAngle,mode==='eclipses'?node:0,earthPos);return <><ambientLight intensity={.055}/><pointLight position={sunPos} intensity={70} distance={18} castShadow shadow-mapSize-width={1024} shadow-mapSize-height={1024} shadow-bias={-.0005}/><Stars radius={30} depth={12} count={900} factor={1.3} fade/><mesh position={sunPos}><sphereGeometry args={[season?.85:1.05,48,48]}/><meshBasicMaterial color="#f2b96b"/></mesh>{season&&<Orbit radius={SEASON_ORBIT_RADIUS}/>}<group position={earthPos}><Earth rotation={mode==='day'?a:0}/>{showMoon&&<Orbit/>}</group>{showMoon&&<mesh position={moon} castShadow receiveShadow><sphereGeometry args={[.25,32,32]}/><meshStandardMaterial color="#aaa9a3" roughness={.9}/></mesh>}{mode==='eclipses'&&<><Line points={[[moon[0],earthPos[1],moon[2]],moon]} color="#708aa0" lineWidth={.6} dashed dashSize={.06} gapSize={.05}/><EclipseShadows moon={moon} earth={earthPos} sun={sunPos} moonAngle={moonAngle}/></>}{mode==='tides'&&<TideFields moonAngle={moonAngle}/>}<OrbitControls enablePan={false} minDistance={5} maxDistance={15} autoRotate={false}/></>}

export default function SkyModel(p:{mode:Mode;value:number;node:number}){return <div className="canvas"><Canvas shadows camera={{position:[0,4.8,10],fov:46}} dpr={[1,1.5]}><Scene {...p}/></Canvas></div>}
